### ISSUE TITLE
doctype missing on design-system.html

### ISSUE THREAD

**Issue by stemlund** [kevin-powell/space-tourism#3]
The HTML doctype is missing in design-system.html and index.html (in probably all lesson files). This caused the following CSS to not work:

.underline-indicators > *:hover 

.dot-indicators > *:hover

When a doctype is added, the above CSS begins working again. Interestingly, the  > *:focus declarations worked fine without a doctype.

I had never realized a missing doctype would have such random issues with CSS declarations, but apparently it does.

**Comment by kevin-powell** [comment]
Oh no... I'd made that change a while back and forgot to push it! I just updated the repo now :)
