### ISSUE TITLE
"aria-expanded" attribute on the "button" element, but not on the "span" element

### ISSUE THREAD

**Issue by RinatValiullov** [kevin-powell/space-tourism#4]
What for do we need set a new `aria-expanded` attribute on the `button` element? Because in `index.js` we get exactly the `button`, not the inner `span`.

https://github.com/kevin-powell/space-tourism/blob/558f56b84625694d126b73de569766ee0af4b279/lesson-files/36/02-end/index.js#L2-L9

<hr>

_Before click on the `button`:_

![image](https://user-images.githubusercontent.com/9755333/151396575-b937fd3e-7be3-4c18-8e79-b397125362fa.png)

_After click on the `button`:_

![image](https://user-images.githubusercontent.com/9755333/151396779-0ab4a9ea-bbfe-4e54-a77b-93b9016d4d78.png)
![image](https://user-images.githubusercontent.com/9755333/151396855-22fe37c4-87d3-4fc1-b7c4-f41648542d0d.png)

**Comment by kevin-powell** [comment]
We don't need the aria-expanded on the span itself. The `aria-expanded` is referring to what the button controls, as defined by the `aria-controls`. The span is just the text that's inside the button.

**Comment by RinatValiullov** [comment]
That's why I made the issue, because in the course (Scrimba) I noticed that we set the `aria-expanded` attribute on the `span`.

https://github.com/kevin-powell/space-tourism/blob/558f56b84625694d126b73de569766ee0af4b279/lesson-files/30/02-end/index.html#L24


Thanks for the quick response 👍

**Comment by kevin-powell** [comment]
Oh no! I misunderstood, sorry about that! I'll dive in and take a look :)
